
services:
  db:
    image: postgres:13
    container_name: postgres-iot
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/create_views.sql:/docker-entrypoint-initdb.d/create_views.sql

volumes:
  postgres_data: